### ISSUE TITLE
app v1-3-1 F-droid constantly crashes on start

### ISSUE THREAD

**Issue by laurentriffard** [ChristopherGittner/OSMBugs#25]
Hi,

I'm using OSMbugs from F-droid on Xiaomi Redmi Note 8T, Android 10.

Since upgrade to v1-3-1, OSMBugs constantly crashes on start. V1-2-2 and previous versions were fine.

Here is a stack trace :
kotlin.UninitializedPropertyAccessException: lateinit property mBinding has not been initialized
	at org.gittner.osmbugs.ui.MainActivity.onPostCreate(MainActivity.kt:40)
	at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1381)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3361)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2046)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7564)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by ChristopherGittner** [comment]
Thanks for the Issue.
I can't really explain, why i didn't check it before committing the release :-/

**Comment by ChristopherGittner** [comment]
It might take a couple of Days before appearing on F-Droid

**Comment by laurentriffard** [comment]
Thank you, I'll wait for it.

**Comment by laurentriffard** [comment]
V 1-3-2 landed on F-Droid.
Issue fixed, thank you.
