### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by opk12** [ChristopherGittner/OSMBugs#28]
Install 1-3-6 or 1-3-5 from f-droid, scroll the map, enable layers, close. Then it cannot be launched again, because it crashes.

```
java.lang.RuntimeException: Unable to create application org.gittner.osmbugs.App: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6013)
	at android.app.ActivityThread.-wrap3(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1727)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6816)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
	at android.app.SharedPreferencesImpl.getLong(SharedPreferencesImpl.java:249)
	at org.gittner.osmbugs.statics.Settings.getCacheSizeMb(Settings.kt:52)
	at org.gittner.osmbugs.App.onCreate(App.kt:76)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6010)
	... 8 more
```

**Comment by opk12** [comment]
Instead, 1-3-4 from f-droid seems not affected. It works and I am using it.

(1-3-4 did crash in the settings: once while scrolling the settings; once by clicking Login in the settings; once by saving the cache size with empty value. But it does not crash on start, so I can use the map.)
