### ISSUE TITLE
Crash in the KeepRight settings

### ISSUE THREAD

**Issue by opk12** [ChristopherGittner/OSMBugs#37]
In the settings, I tap on the button to list the KeepRight errors. The app crashes.

```
FATAL EXCEPTION: main
Process: org.gittner.osmbugs, PID: 6836
android.content.res.Resources$NotFoundException: Drawable org.gittner.osmbugs:string/pref_keepright_enabled_20 with resource ID #0x7f1001fe
Caused by: android.content.res.Resources$NotFoundException: File pref_keepright_enabled_20 from drawable resource ID #0x7f1001fe
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:775)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:621)
	at android.content.res.Resources.getDrawable(Resources.java:1646)
	at androidx.core.content.res.ResourcesCompat$Api21Impl.getDrawable(ResourcesCompat.java:701)
	at androidx.core.content.res.ResourcesCompat.getDrawable(ResourcesCompat.java:137)
	at org.gittner.osmbugs.statics.Images$Companion.GetDrawable(Images.kt:20)
	at org.gittner.osmbugs.keepright.KeeprightSelectErrorsDialog.onCreateDialog(KeeprightSelectErrorsDialog.kt:34)
	at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:930)
	at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:844)
	at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1755)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:527)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6816)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
Caused by: java.io.FileNotFoundException: pref_keepright_enabled_20
	at android.content.res.AssetManager.openNonAssetNative(Native Method)
	at android.content.res.AssetManager.openNonAsset(AssetManager.java:515)
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:768)
	... 22 more
```

I am on 1.4.0 from F-droid on Samsung Android 7.1.

**Comment by mnalis** [comment]
I can confirm crash on 1.4.0 from F-droid on Samsung Android 14. 
(I recall it used to work in previous versions...)
