### ISSUE TITLE
Crash after setting cache size

### ISSUE THREAD

**Issue by opk12** [ChristopherGittner/OSMBugs#39]
- Install version 1.4.0 from F-droid.
- Open the settings.
- Tap the button to set the cache size.
- Type a number and press Ok.
- Close the app.
- The app crashes whenever you try to open it.
- The fix is to uninstall and reinstall.

```
FATAL EXCEPTION: main
Process: org.gittner.osmbugs, PID: 14864
java.lang.RuntimeException: Unable to create application org.gittner.osmbugs.App: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6013)
	at android.app.ActivityThread.-wrap3(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1727)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6816)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
	at android.app.SharedPreferencesImpl.getLong(SharedPreferencesImpl.java:249)
	at org.gittner.osmbugs.statics.Settings.getCacheSizeMb(Settings.kt:50)
	at org.gittner.osmbugs.App.onCreate(App.kt:93)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6010)
	... 8 more
```

I am on Samsung Android 7.1.

**Comment by mnalis** [comment]
I can confirm same issue on Samsung Galaxy S23+ (Android 14), after upgrade to F-droid OSMBugs`1.4.0`.
(after closing I have to remove it from recent apps lists to fully close it) 

Upon crash on subsequent start attempt, Samsung oneUI offers to clear the cache for the app, but that does not help. Only uninstall/reinstall (or manually clearing all app data from Android settings) allows the OSMBugs to start again.

**Comment by opk12** [comment]
Just a heads up that I can't reproduce this on 1.4.1. Thank you
